name: GH-PAGE
# 设置push触发流水线
on:
  push:
    branches: master
jobs:
  RELEASE_BLOG:
    runs-on: ubuntu-latest
    steps:
      # 拉取项目代码
      - name: Checkout repository
        uses: actions/checkout@v2
      # 给当前环境下载node
      - name: Use Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: "12.x"
      # 安装依赖
      - name: Installing Dependencies
        run: npm install
      # 运行脚本
      - name: Runner Deploy.sh
        run: npm run deploy