name: PUSH_DEPLOY
# 设置push触发流水线
on:
  push:
    branches: master
jobs:
  # 只需要定义一个job并命名为DEPLOY_BLOG
  DEPLOY_BLOG:
    runs-on: ubuntu-latest
    steps:
      # 拉取项目代码
      - name: Checkout repository
        uses: actions/checkout@v2
      # 给当前环境下载node
      - name: Use Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: "12.x"
      # 安装依赖
      - name: Installing Dependencies
        run: npm install
      - name: GitHub Push
        # You may pin to the exact commit or the version.
        # uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        uses: ad-m/github-push-action@v0.6.0
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
          repository: 'git@github.com:liuk123456789/my-blog.git'
          # Destination branch to push changes
          branch: master:gh-pages
