name: PUSH_DEPLOY
# 设置push触发流水线
on:
  push:
    branches: master
jobs:
  # 只需要定义一个job并命名为DEPLOY_BLOG
  DEPLOY_BLOG:
    runs-on: ubuntu-latest
    steps:
      # 拉取项目代码
      - name: Checkout repository
        uses: actions/checkout@v2
      # 给当前环境下载node
      - name: Use Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: "12.x"
      # 安装依赖
      - name: Installing Dependencies
        run: npm install
      - name: Cobalt deploy gh-pages
        # You may pin to the exact commit or the version.
        # uses: saidgeek/cobalt-deploy-gh-pages@1cacc6d9853c34da0b29a61c8114fec2df5de0cd
        uses: saidgeek/cobalt-deploy-gh-pages@v1.0.0
        with:
          # Personal Access Token with permission to the repository
          githubToken: ${{secrets.GITHUB_TOKEN}}
          # Repository to push building page
          repo: liuk123456789/my-blog
          # Branch to push building page
          branch: gh-pages
