name: DEPLOY
# 设置push触发流水线
on:
  push:
    branches: master
jobs:
  # 只需要定义一个job并命名为DEPLOY_BLOG
  DEPLOY_BLOG:
    runs-on: ubuntu-latest
    steps:
      # 拉取项目代码
      - name: Checkout repository
        uses: actions/checkout@v2
      # 给当前环境下载node
      - name: Use Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: "12.x"
      # 安装依赖
      - name: Installing Dependencies
        run: npm install
      # 打包
      - name: Build
        # 打包应用
        run: npm run build
      # 拷贝打包的资源public
      - name: Copy Public file with SCP
        uses: appleboy/scp-action@v0.0.1
        with: 
          host: ${{secrets.SECRET_HOST}}
          username: ${{secrets.SECRET_NAME}}
          password: ${{secrets.SECRET_PWD}}
          port: 22
          souce: 'public/'
          target: ${{secrets.SECRET_TARGET}}
