name: DEPLOY
# 设置push触发流水线
on:
  push:
    branches: master
jobs:
  # 只需要定义一个job并命名为DEPLOY_BLOG
  DEPLOY_BLOG:
    runs-on: ubuntu-latest
    steps:
      # 拉取项目代码
      - name: Checkout repository
        uses: actions/checkout@v3
      # 给当前环境下载node
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      # 安装依赖
      - name: Installing Dependencies
        run: npm install
      # 打包
      - name: Build
        # 打包应用
        run: npm run build
      # 拷贝打包的资源public
      - name: copy file via ssh password
        # 因为构建之后，需要把代码上传到服务器上，所以需要连接到ssh，并且做一个拷贝操作
        uses: cross-the-world/scp-pipeline@master
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          pass: ${{ secrets.REMOTE_PASS }}
          connect_timeout: 10s
          local: './public/*'
          remote: /home/my-blog
      - name: Deploy GitHub Pages site
        # uses: crazy-max/ghaction-github-pages@c0d7ff0487ee0415efb7f32dab10ea880330b1dd
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
