name: DEPLOY
# 设置push触发流水线
on:
  push:
    branches: master
jobs:
  # 只需要定义一个job并命名为DEPLOY_BLOG
  DEPLOY_BLOG:
    runs-on: ubuntu-latest
    steps:
      # 拉取项目代码
      - name: Checkout repository
        uses: actions/checkout@v2
      # 给当前环境下载node
      - name: Use Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: "12.x"
      # 安装依赖
      - name: Installing Dependencies
        run: npm install
      # 打包
      - name: Build
        # 打包应用
        run: npm run build
      # 拷贝打包的资源public
      - name: copy file via ssh password
        # 因为构建之后，需要把代码上传到服务器上，所以需要连接到ssh，并且做一个拷贝操作
        uses: cross-the-world/scp-pipeline@master
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          pass: ${{ secrets.REMOTE_PASS }}
          connect_timeout: 10s
          local: './public/*'
          remote: /home/my-blog
        - name: Deploy gh-pages
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages # The branch the action should deploy to.
            FOLDER: public # The folder the action should deploy.
